version: '3.8'
# include:
#   - path: ./cr-api/deploy/docker/docker-compose.yml

services:
  wazuh:
    image: wazuh/wazuh-indexer:4.14.0
    ports:
      - 9201:9200

  # opensearch:
  #   image: opensearchproject/opensearch:latest
  #   environment:
  #    - discovery.type=single-node
  #    - DISABLE_SECURITY_PLUGIN=true
  #   ports:
  #     - 9200:9200
  #     - 9600:9600

# networks:
#     - integrador
# volumes:
  # db_data:
